### ISSUE TITLE
Error on Export to ISBI challenge file format

### ISSUE THREAD

**Issue by TroySeman** [trackmate-sc/TrackMate#246]
The is the error I get when I select "Export to ISBI challenge file format" after I click "Execute"

Exception in thread "TrackMate action thread" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at fiji.plugin.trackmate.action.ISBIChallengeExporter.execute(ISBIChallengeExporter.java:80)
	at fiji.plugin.trackmate.gui.components.ActionChooserPanel$1$1.run(ActionChooserPanel.java:99)

**Comment by tinevez** [comment]
Hello.
I could not reproduce the bug with the current TrackMate and demo image.
Can you give me a MWE to reproduce the bug?
<img width="1476" alt="Screenshot 2023-03-06 at 10 13 11" src="https://user-images.githubusercontent.com/3583203/223066892-3961f215-a69e-477d-bf07-4c9c04e42bd2.png">

**Comment by TroySeman** [comment]
What is MWE?

**Comment by tinevez** [comment]
Minimal working example. Steps for me to reproduce the bug on my side.

**Comment by TroySeman** [comment]
I was going through the job settings wizard just now and the software just worked for the first time.  I'm not sure why.  I know trackmate had an update last night but I did restart imagJ.  Please disregard this error report and thank you for your time and attention.
