### ISSUE TITLE
Trackmate is not loading properly

### ISSUE THREAD

**Issue by Aneenamohan** [trackmate-sc/TrackMate#292]
Hi,
I have been using Trackmate for tracking ring like moving structures to get their pathway. 
I usually do the tracking as the following path 
File -> Open -> my file -> tick on  covert to grey scale   -> ok
Image -> duplicate -> tick on duplicate stack -> ok
Plugin -> Tracking -> Trackmate

Lately, whenever I try to use Trackmate plugin, it always open another window(exception) which says

(Fiji Is Just) ImageJ 2.14.0/1.54f; Java 1.8.0_322 [64-bit]; Windows 10 10.0; 53MB of 2000MB (2%)
 
java.lang.IllegalArgumentException: (minimum <= value <= maximum) is false
	at javax.swing.SpinnerNumberModel.<init>(SpinnerNumberModel.java:125)
	at javax.swing.SpinnerNumberModel.<init>(SpinnerNumberModel.java:164)
	at fiji.plugin.trackmate.gui.components.ConfigureViewsPanel.<init>(ConfigureViewsPanel.java:338)
	at fiji.plugin.trackmate.gui.wizard.descriptors.ConfigureViewsDescriptor.<init>(ConfigureViewsDescriptor.java:45)
	at fiji.plugin.trackmate.gui.wizard.TrackMateWizardSequence.<init>(TrackMateWizardSequence.java:148)
	at fiji.plugin.trackmate.TrackMatePlugIn.createSequence(TrackMatePlugIn.java:118)
	at fiji.plugin.trackmate.TrackMatePlugIn.run(TrackMatePlugIn.java:99)
	at fiji.plugin.trackmate.TrackMateRunner.run(TrackMateRunner.java:529)
	at ij.IJ.runUserPlugIn(IJ.java:244)
	at ij.IJ.runPlugIn(IJ.java:210)
	at ij.Executer.runCommand(Executer.java:152)
	at ij.Executer.run(Executer.java:70)
	at java.lang.Thread.run(Thread.java:750)

Can you suggest the solution for this problem so that I can resume my work as soon as possible?

**Comment by tinevez** [comment]
Hello

This comes from a misconfiguration. I will make some code to avoid it happening again.
In the meantime you can delete the `lastusedsettings.xml` file in the `.trackmate/` folder in your home directory.

**Comment by Aneenamohan** [comment]
Hi, I have deleted the lastusedsettings.xml file in the .trackmate/ folder in my home directory. This is just to enquire whether you have rectified the problem or not. I would appreciate it if you could make the said code urgently.

**Comment by tinevez** [comment]
Hello @Aneenamohan 
but did it work for you?

**Comment by tinevez** [comment]
Hello ?
